var bool=true;
$(".menu").click(function(){
    if(bool){
        bool=false;
        $(".menu").animate({
            rotate:"90deg"
        });
        $(".m1").animate({
            rotate:"30deg"
        });
        $(".m2").css("visibility","hidden");
        $(".m3").animate({
            rotate:"-30deg"
        });
        $(".in-menu").css("visibility","visible");
        $(".in-menu").css("display","flex");
    }
    else{
        bool=true;
        $(".menu").animate({
            rotate:"0deg"
        });
        $(".menu>*").animate({
            rotate:"0deg"
        },50);
        $(".m2").css("visibility","visible");
        
        $(".in-menu").css("visibility","hidden");
        $(".in-menu").css("display","none");
    }
});